# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jiracli < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    url "https://github.com/rhysjtevans/jiracli/releases/download/0.0.2/jiracli_0.0.2_darwin_amd64.tar.gz"
    sha256 "a75473a854645a0d33966451d2e8499cb5453084898be2e9af850fae92a16ff4"

    def install
      bin.install "jiracli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Jiracli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rhysjtevans/jiracli/releases/download/0.0.2/jiracli_0.0.2_linux_amd64.tar.gz"
      sha256 "baad8d33e7a47b38393f27f5ae04a79f0e840516a86df7ad5e6bdce7051accb5"

      def install
        bin.install "jiracli"
      end
    end
  end
end
